---
- name: Configurar servidor db
  hosts: db
  become: yes

  vars:
    mount_point: /var/nfs
    remote_share: 192.168.56.121:/dados/nfs

  tasks:
    - name: Instalar mariadb-server
      apt:
        name: mariadb-server
        state: present
        update_cache: yes

    - name: Instalar autofs
      apt:
        name: autofs
        state: present

    - name: Configurar montagem automática via autofs
      blockinfile:
        path: /etc/auto.master
        marker: "# {mark} ANSIBLE-NFS-MOUNT-DB"
        block: |
          {{ mount_point }} /etc/auto.nfs --ghost

    - name: Criar arquivo de configuração /etc/auto.nfs
      copy:
        dest: /etc/auto.nfs
        content: |
          share -rw,soft,intr {{ remote_share }}
        owner: root
        group: root
        mode: '0644'

    - name: Criar ponto de montagem local
      file:
        path: "{{ mount_point }}"
        state: directory
        mode: '0755'

    - name: Reiniciar e habilitar o serviço autofs
      service:
        name: autofs
        state: restarted
        enabled: yes
