---
- name: Configurar servidor DHCP autoritativo no arq
  hosts: arq
  become: yes

  vars:
    db_mac: "AA:BB:CC:DD:EE:01"
    app_mac: "AA:BB:CC:DD:EE:02"

  tasks:
    - name: Instalar pacote isc-dhcp-server
      apt:
        name: isc-dhcp-server
        state: present
        update_cache: yes

    - name: Definir interface do DHCP (eth1)
      lineinfile:
        path: /etc/default/isc-dhcp-server
        regexp: '^INTERFACESv4='
        line: 'INTERFACESv4="eth1"'

    - name: Criar arquivo de configuração dhcpd.conf
      copy:
        dest: /etc/dhcp/dhcpd.conf
        content: |
          authoritative;

          option domain-name "clara.rebeca.devops";
          option domain-name-servers 1.1.1.1, 8.8.8.8;
          default-lease-time 600;
          max-lease-time 7200;

          subnet 192.168.56.0 netmask 255.255.255.0 {
            range 192.168.56.50 192.168.56.100;
            option routers 192.168.56.1;
          }

          host db.clara.rebeca.devops {
            hardware ethernet {{ db_mac }};
            fixed-address 192.168.56.109;
          }

          host app.clara.rebeca.devops {
            hardware ethernet {{ app_mac }};
            fixed-address 192.168.56.19;
          }

    - name: Reiniciar o serviço DHCP
      service:
        name: isc-dhcp-server
        state: restarted
        enabled: yes

