---
- name: Configurar NFS no servidor arq
  hosts: arq
  become: yes

  vars:
    nfs_user: nfs-ifpb
    shared_dir: /dados/nfs
    subnet: 192.168.56.0/24

  tasks:
    - name: Instalar o servidor NFS
      apt:
        name: nfs-kernel-server
        state: present
        update_cache: yes

    - name: Garantir que o ponto de montagem /dados existe
      file:
        path: /dados
        state: directory
        mode: '0755'

    - name: Criar usu치rio nfs-ifpb sem shell
      user:
        name: "{{ nfs_user }}"
        shell: /usr/sbin/nologin
        create_home: yes
        state: present

    - name: Criar diret칩rio compartilhado
      file:
        path: "{{ shared_dir }}"
        state: directory
        owner: "{{ nfs_user }}"
        group: "{{ nfs_user }}"
        mode: '0750'

    - name: Obter UID do usu치rio nfs-ifpb
      getent:
        database: passwd
        key: "{{ nfs_user }}"
      register: nfs_passwd

    - name: Obter GID do grupo nfs-ifpb
      getent:
        database: group
        key: "{{ nfs_user }}"
      register: nfs_group

    - name: Armazenar UID e GID como vari치veis
      set_fact:
        nfs_uid: "{{ nfs_passwd.getent[1] }}"
        nfs_gid: "{{ nfs_group.getent[1] }}"

    - name: Configurar /etc/exports
      copy:
        dest: /etc/exports
        content: |
          {{ shared_dir }} {{ subnet }}(rw,sync,no_subtree_check,all_squash,anonuid={{ nfs_uid }},anongid={{ nfs_gid }})
      notify: Restart NFS

  handlers:
    - name: Restart NFS
      service:
        name: nfs-kernel-server
        state: restarted
        enabled: yes
